name: Run Python Proxy

on:
  workflow_dispatch:   # Bisa dijalankan manual dari GitHub

jobs:
  run-proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run proxy-server.py
        run: |
          python proxy-server.py
